"""add_recipient_name_and_error_message_to_receipts

Revision ID: aabf52740fe0
Revises: 69b106eff1e2
Create Date: 2026-04-26 13:20:13.031055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabf52740fe0'
down_revision: Union[str, Sequence[str], None] = '69b106eff1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('recipient_name', sa.String(), nullable=True))
    op.add_column('receipts', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'error_message')
    op.drop_column('receipts', 'recipient_name')
    # ### end Alembic commands ###
